# Prod environment
variables:

  # Global
  ap_vm_image: ubuntu-20.04

  namespace: demoworkspace # Updated namespace
  postfix: 001 # Updated postfix
  location: eastus # Updated location

  environment: prod
  enable_aml_computecluster: true
  enable_aml_secure_workspace: true
  enable_monitoring: false

  # Azure DevOps
  ado_service_connection_rg: Azure-ARM-Prod
  ado_service_connection_aml_ws: Azure-ARM-Prod

# Trigger the run
  # For pipeline reference
  resource_group: "glmsftai-subri"
  aml_workspace: "b747ee09-a6bb-42d4-a775-5c4150b98e67"
